### ISSUE TITLE
Вопрос по патчам

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/pg_query_state#4]
Добрый день,
в описании инсталяции сказано:
```
To install pg_query_state, please apply patches custom_signal.patch, executor_hooks.patch and runtime_explain.patch to the latest stable version of PostgreSQL and rebuild PostgreSQL.
```
скажите пожалуйста, указанные патчи в ванильной версии постгреса 10.2 уже есть или их как-то надо туда применить?
Можно ли безпроблемно использовать текущую версию кода с ванильным постгрессом 10.2 ?

**Comment by maksm90** [comment]
Привет @sgrinko !

К сожалению, постгрес 10.2 также необходимо патчить. Сейчас я работаю над проталкиванием критического патча в сообщество [1], после которого уже можно будет и это расширение, и многие другие интересные решения реализовывать в виде полноценного extension'а. Можете поддержать мой патч в сообществе или записаться ревьювером [2].

1. https://www.postgresql.org/message-id/a95ba3c0-f4aa-fcfc-1786-b765f6caea44%40gmail.com
2. https://commitfest.postgresql.org/17/1430/
