### ISSUE TITLE
how to apply patches custom_signal.patch, executor_hooks.patch and runtime_explain？

### ISSUE THREAD

**Issue by msdnchina** [postgrespro/pg_query_state#5]
To install pg_query_state, please apply patches custom_signal.patch, executor_hooks.patch and runtime_explain.patch to the latest stable version of PostgreSQL and rebuild PostgreSQL. -----I want to know， how to apply patches custom_signal.patch, executor_hooks.patch and runtime_explain？？

Thank you very much！

**Comment by maksm90** [comment]
Hello @msdnchina!

You have to:

1. Checkout `pg_query_state` to the branch that corresponds to your postgres intallation.

    - PG9_5 - for PostgreSQL9.5
    - PGPRO9_6 - for PostgreSQL9.6
    - PGPRO10 - for PostgreSQL10

2. Execute the one of the following commands in the postgres source code root directory:
`git apply path/to/*.patch`
or
`patch -p1 < path/to/*.patch`

If you'll notice some conflicts, please report me. I'll immediately try to fix it.

**Comment by msdnchina** [comment]
I find that： in the  “pg_query_state-PGPRO10.zip” file，there is no “executor_hooks.patch” ----Is this correct？

**Comment by msdnchina** [comment]
hi, when I apply patch, the following error happened:
[root@pgserver postgresql-10.2]# git apply /root/pg_query_state-PGPRO10/*.patch
error: patch failed: src/include/storage/procsignal.h:51
error: src/include/storage/procsignal.h: patch does not apply
[root@pgserver postgresql-10.2]# pwd
/root/postgresql-10.2
[root@pgserver postgresql-10.2]#

**Comment by maksm90** [comment]
> I find that： in the “pg_query_state-PGPRO10.zip” file，there is no “executor_hooks.patch” ----Is this correct？

Yes, _executor_hooks.patch_ is intended only for testing extension on postgres 9.5. I have removed the notice about it from README.

> when I apply patch, the following error happened

Thanks a lot for your report. I have put updated version of patches and extension itself into separate branch _PG10_. You can use it.
